# Generated by Django 2.0.5 on 2018-05-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.TextField(default='')),
                ('place', models.IntegerField(choices=[(0, 'street'), (1, 'ortanization')])),
                ('place_desciption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=200, unique=True)),
                ('agency_name', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='newsevent',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map_app.ParsedNews'),
        ),
    ]
