# Generated by Django 2.0.5 on 2018-05-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsevent',
            old_name='place_desciption',
            new_name='place_description',
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='place',
            field=models.IntegerField(choices=[(0, 'street'), (1, 'organization')]),
        ),
    ]
